---
title: "Assingments"
---

## Portfolio assessment {#sec-portfolio}

-   In order to be able to adapt the assignments flexibly to the requirements of the course (e.g. different number of students, projects changing from semester to semester or several projects in one semester), this seminar uses a `portfolio` assessment. Even though the seminar aims at testing new forms of assignments due to its practical and empirical orientation, traditional assignments such as presentations or written reports will still be an integral part. However, these will be expanded to include the special features of working with digital behavioral data.
-   Assignments can be group (👥) or individual (👤) work and are marked as such. The expected group size is 2-4 persons.
-   The following list contains an overview of the assignments to be completed in the course:

| Assignment | 100 Pts |
|---------------------------------|---------------------------------------|
| [👥 Presentation: 📚 Theory](#sec-presentation) | 30 Pts |
| [👥 Presentation: 📊 Research Project](#sec-research-project-presentation) | 15 Pts |
| [👤 Peer Review](#sec-peer-review) | 15 Pts |
| [👥 Written assignment: Final Project Report](#sec-written-report) | 40 Pts |

: Breakdown of the final grade

::: callout-caution
## Important Disclaimer

-   **The final structure of the course (e.g. which and how many small projects) will be discussed and determined together with the students in the first session.** Accordingly, it is possible that the portfolio or the assignments contained in it will be adjusted subsequently (e.g. the scope, content or deadline of assignments could be changed or even entire assignments could be dropped).
:::

## 👥 Presentation : 📚 Theory (20 Pts) {#sec-presentation}

The topics for the presentation will be assigned at the beginning of the course. The presentation should be 20 to 30 minutes long (including time for questions and discussion). Literature for the preparation of the presentation will be provided. The texts relevant for the respective presentation can be found in the information on the preparation (📖) of the respective session. All texts listed in the section "*Mandatory literature*" constitute the presentation literature for your respective presentation and will be provided. Please include all texts on your topic in your presentation, but feel free to set your own priorities in the presentation. You may also cite other sources, provided they enrich the subject matter.

The aim of the presentation is to give the course participants an overview on your topic, e.g., central terms, definitions and features of the respective platform, method and/or tool. The presentation of the state of research (what is the goal of the studies and what do they show?) plays a subordinate role.

### Feedback meeting before the presentation (mandatory)

Additionally, presenters are required to meet with the instructor in the week before their presentation for a mandatory feedback. My office hours are directly after the session, on *Wednesdays from 15:30 to 16:30*. If you have scheduling conflicts, we can arrange another meeting time. Meetings can take place in person or via Zoom.

<!-- TODO Optional: Add information about booking of feedback slot -->

In advance of the feedback meeting, a first complete draft of the presentation must be submitted as a PowerPoint or PDF file via mail at the latest until 12:00 the day before the meeting, one week before the presentation. During the feedback meeting, students will receive detailed feedback and tips on how to revise their presentation. The revised presentations are then given in presence in the respective sessions. Afterwards, a PDF of the slides is made available to the seminar.

### Feedback after the presentation (optional)

If you would like to receive feedback on your presentation after the session, please let me know during the mandatory feedack meeting. The feedback will take place directly after the event (15:00 to 15:30). The aim of this feedback is to give you a first impression directly after the presentation. However, there will be no (assessment of) the presentation in the discussion.

::: callout-tip
## Important information, tasks & deadlines

-   ℹ️ You will be graded based on your individual contribution, so please clarify which slides are presented by whom (e.g., by adding the initials of the presenting individual in the footnote of the slide).
-   ⏰ *One week before your presentation:* feedback meeting to discuss the presentation draft during the office hours. Please arrange an alternative date in good time if you are unable to attend the scheduled feedback meeting.
-   ⏰ *At the latest at 12:00 the day before the feedback meeting:* Send the first complete draft of the presentation slides by e-mail to [christoph.](mailto:christoph.adrian@fau.de?subject=Entwurf%20Präsentation%20DBD)[adrian](mailto:christoph.adrian@fau.de?subject=Draft%20Presentation%20DBD)[\@fau.de](mailto:christoph.adrian@fau.de?subject=Entwurf%20Präsentation%20DBD)
-   ⏰ *Until 09:00 of the day of the presentation:* Send the final draft of the presentation by e-mail to [christoph.adrian\@fau.de](mailto:christoph.adrian@fau.de?subject=Presentation%20DBD)
:::

## 👥 Presentation: 📊 Research Project (15 Pts) {#sec-research-project-presentation}

In this presentations you will present your research project, including (preliminary) results. The presentation should be 15 to 20 minutes long (with additional 10 minutes for questions and discussion). The aim of the presentation is to give the course an overview of your project and to get feedback on your research question, methodology and analysis, that can be included into the written report. Therefore, you should include the following points in your presentation:

#### Section 1 - Introduction (2-3 slides)

The introduction section includes

-   an introduction to the subject matter you're investigating
-   the motivation for your research question (citing relevant literature)
-   the general research question you wish to explore and/or your hypotheses regarding the research question of interest.

#### Section 2 - Method description (2 slides)

In this section, you will describe the method and data (sub-)sample you selected. This includes

-   description of the "observations" included in the data set,
-   motivations for the selection of your specific subsample,
-   analytical approach with which you want to answer the research question/hypothesis,
-   description of the central method(s) as well as necessary pre-processing steps.

#### Section 3 - Results and Discussion (2-3 slides)

In this section, you will provide a brief overview of your (preliminary) results. This includes

-   description, visualization and/or summary statistics of the central variables,
-   (preliminary) results of the central method(s) you used,
-   (optionally) a challenge you face and want to discuss with the course.

These presentations are the basis for the peer review and the final written report. Therefore, you should use the feedback you receive to improve your project and the final report.

::: callout-tip
## Important information, tasks & deadlines

-   ℹ️ You will be graded as a group (unless explicitly requested otherwise). Not every group member has to present, but all group members should contribute and be able to answer questions about the project.
-   ℹ️ The presentations will be the basis for the Peer Review assignment. In order to simplify the process, please use the Google-Slide template provided to your group.
-   ⏰ *Until the 15.01.2025:* Finalize the presentation (Goolge Slides). On the 16.01., the presentation will be changed to non-editable and make available for peer review. After the peer-review process, the presentation will be "unlocked" and you can make changes again.
:::

## 👤 Peer Review (15 Pts) {#sec-peer-review}

Critically reviewing others' work is a crucial part of the scientific process. Therefore, each person will be assigned two other group's research project presentations to review before their presentation. This way, you will be able to get additional feedback before presenting your results to the whole course.

During the peer review process, you will be provided with

-   read-only access to two group presentations via Google Slides. Although the slides should be non-editable, please to not try to change and do not share the slides.
-   a link to a digital peer review form. The form contains both short item scales and open-ended questions. The aim is to summarize the content of the presentation very briefly, evaluate it and make suggestions for improvement.

<!-- TODO Add information about the peer review process -->

```{=html}
<!-- #### Process and questions

-   Open the Google Doc of the team you're reviewing and read their project draft.

-   Then, go to Peer Review Google Doc template, fill out the relevant fields and answer the following questions:

    -   *Describe the goal of the project.*
    -   *Describe the data used or collected, if any. If the proposal does not include the use of a specific dataset, comment on whether the project would be strengthened by the inclusion of a dataset.*
    -   *Describe the approaches, tools, and methods that will be used.*
    -   *Is there anything that is unclear from the proposal?*
    -   *Provide constructive feedback on how the group might be able to improve their project. Make sure your feedback includes at least one comment on the statistical modeling aspect of the project, but do feel free to comment on aspects beyond the modeling.*
    -   *What aspect of this project are you most interested in and would like to see highlighted in the presentation.*
    -   *Provide constructive feedback on any issues with file and/or code organization.*
    -   *(Optional) Any further comments or feedback?* -->
```

::: callout-tip
## Important tasks & deadlines

-   ℹ️ The peer review will be graded on the extent to which it comprehensively and constructively addresses the components of the other groups presentation: the research context and motivation, data analysis, modeling, interpretations, and conclusions.
-   ⏰ *Between 15.01. and 22.01*: Fill out the peer review form for the two assigned groups.
:::

## 👥 Written short report (40 Pts) {#sec-written-report}

The goal of the written short report is for each group to use at least one of the method or data presented to explore a topic of your own choosing. Choose both data and topic based on your group's interests, experience or work you all have done in other courses or research projects. The goal of this project is for you to demonstrate proficiency in the techniques covered in this class (and beyond, if you like!) and apply them to a data set to analyze it in a meaningful way.

Be selective in what you include in your final write-up. The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than explain every step of the analysis. You are welcome to include an appendix with additional work at the end of the written report document; however, grading will largely be based on the content in the main body of the report. You should assume the reader will not see the material in the appendix unless prompted to view it in the main body of the report. The appendix should be neatly formatted and easy for the reader to navigate. It is not included in the word limit.

The written report should be **750 to 1000 words per person**. However, **when written as a group report, the number or words scale with a factor of 0.8 per person** (e.g., a group of two should write 1200 to 1600 words, a group of three 1800 to 2400 words). All analyses as well as the written report must be done in RStudio and all components of the project must be reproducible. The mandatory components of the reports are: *Introduction, Data/Methodology, Results, Discussion & Conclusion*. You are free to add additional sections as necessary. You will be graded based on your individual contribution, so please clarify which part of the report was written by whom (e.g., by adding the initials of the author in the header of the section).

The written report is worth 40 points, broken down as follows

| Total                       | 40 pts |
|-----------------------------|--------|
| *Introduction + Theory*     | 6 pts  |
| *Methodology/Data*          | 10 pts |
| *Results*                   | 14 pts |
| *Discussion + conclusion*   | 6 pts  |
| *Organization + formatting* | 4 pts  |

::: callout-tip
## Important tasks & deadlines

-   Final submission of the revised written report is due *02.03.2024, 23:59*[^1]*.*
:::

[^1]: Please note that this is a temporary deadline. The final deadline will be adjusted in the course in consultation with the students if necessary.